# Generated by Django 3.0.5 on 2020-05-02 19:02

from django.db import migrations, models
import pms_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_api', '0002_auto_20200502_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='base_image',
            field=models.ImageField(max_length=255, upload_to=pms_api.models.Image.base_image_directory),
        ),
        migrations.AlterField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, max_length=255, upload_to=pms_api.models.Image.processed_image_directory),
        ),
    ]
