# Generated by Django 3.0.5 on 2020-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_api', '0003_auto_20200502_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, default=0),
            preserve_default=False,
        ),
    ]
