# Generated by Django 3.0.5 on 2020-05-02 13:59

from django.db import migrations, models
import pms_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_image', models.ImageField(max_length=255, upload_to=pms_app.models.Image.base_image_directory)),
                ('processed_image', models.ImageField(blank=True, max_length=255, upload_to=pms_app.models.Image.processed_image_directory)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
