# Generated by Django 3.0.5 on 2020-05-02 18:10

from django.db import migrations, models
import pms_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='base_image',
            field=models.FileField(max_length=255, upload_to=pms_app.models.Image.base_image_directory),
        ),
        migrations.AlterField(
            model_name='image',
            name='processed_image',
            field=models.FileField(blank=True, max_length=255, upload_to=pms_app.models.Image.processed_image_directory),
        ),
    ]
